export const PRIVACY_FINDING_CODES = {
  PRECISE_GPS_LOCATION: "PRECISE_GPS_LOCATION",
  DEVICE_SERIAL_IDENTIFIER: "DEVICE_SERIAL_IDENTIFIER",
  OWNER_OR_CREATOR_IDENTITY: "OWNER_OR_CREATOR_IDENTITY",
  CREATOR_CONTACT_INFORMATION: "CREATOR_CONTACT_INFORMATION",
  PRECISE_CAPTURE_TIME: "PRECISE_CAPTURE_TIME",
  SOFTWARE_TRACE: "SOFTWARE_TRACE",
} as const;

export type PrivacyFindingCode =
  (typeof PRIVACY_FINDING_CODES)[keyof typeof PRIVACY_FINDING_CODES];
