export const INSPECTION_ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  UNSUPPORTED_FORMAT: "UNSUPPORTED_FORMAT",
  FILE_READ_FAILED: "FILE_READ_FAILED",
  CORRUPTED_METADATA: "CORRUPTED_METADATA",
  PARSER_FAILED: "PARSER_FAILED",
  UNSUPPORTED_METADATA_BLOCK: "UNSUPPORTED_METADATA_BLOCK",
  ABORTED: "ABORTED",
} as const;

export type InspectionErrorCode =
  (typeof INSPECTION_ERROR_CODES)[keyof typeof INSPECTION_ERROR_CODES];
