export const INTEGRITY_FINDING_CODES = {
  MALFORMED_METADATA_BLOCK: "MALFORMED_METADATA_BLOCK",
  INVALID_GPS_COORDINATES: "INVALID_GPS_COORDINATES",
  INVALID_ORIENTATION_VALUE: "INVALID_ORIENTATION_VALUE",
  INVALID_IMAGE_DIMENSIONS: "INVALID_IMAGE_DIMENSIONS",
  TIMESTAMP_CONFLICT: "TIMESTAMP_CONFLICT",
  IDENTITY_METADATA_CONFLICT: "IDENTITY_METADATA_CONFLICT",
} as const;

export type IntegrityFindingCode =
  (typeof INTEGRITY_FINDING_CODES)[keyof typeof INTEGRITY_FINDING_CODES];
